spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer-service
              uri: http://localhost:4000
              predicates:
                - Path=/api/v1/customers/**
            - id: account-service
              uri: http://localhost:4002
              predicates:
                - Path=/api/v1/accounts/**

server:
  port:
    8082