### Creates a new client entity
POST http://localhost:8082/api/v1/customers
Content-Type: application/json

{
  "name": "Stephanie",
  "lastname": "Azorsa",
  "dni": "12345678",
  "email": "steph.azor@gmail.com",
  "registeredDate": "2025-08-28"
}

###