### Creates a new client entity
POST http://localhost:8082/api/v1/customers
Content-Type: application/json

{
  "name": "Test",
  "lastname": "Test",
  "dni": "44444444",
  "email": "test.test@example.com",
  "registeredDate": "2025-08-28"
}

###