### POST a withdraw from an account

POST http://localhost:8082/api/v1/transactions/withdraw
Content-Type: application/json

{
  "accountId": "a1b2c3d4-e5f6-7890-1234-ef1234567890",
  "amount": 550.50
}
###